#!/bin/bash

WATCHLIST="/app/composer.lock /app/public/"
WEBROOT="/app/public.built"
LOCKFILE="/app/tmp/rebuild.lock"
# WORKINGDIR="/app"

#
# End Configs
#

while true; do
    NEWFILES=`find $WATCHLIST -newer $WEBROOT`
    # echo "${NEWFILES}"
    # if [ ! -d "${NEWFILES}" ]; then
        if [ ! -z "${NEWFILES}" ]; then
            # echo "dos"
            if [ ! -f ${LOCKFILE} ]; then
                # echo "tres"
                # echo "dog"
                touch ${LOCKFILE}
                rsync --exclude themes/sprout-challenge/node_modules/ --exclude themes/sprout-challenge/bower_components/ -r /app/public/wp-content/* /app/public.built/wp-content
                rm ${LOCKFILE}
            fi
        else
            sleep 0
        fi
    # fi
done
